fweanapp/urls.py
from django.urls import path

from .views import *
from django.conf.urls import handler404

app_name = "fweanapp"

urlpatterns = [

path('admin-dashboard/',AdminDashboardView.as_view(), name = 'admindashboard' ),


path('admin/organization/create/', AdminOrganizationCreateView.as_view(), name = 'adminorganizationcreate'),
path('admin/organization/update/<int:pk>/', AdminOrganizationUpdateView.as_view(), name = 'adminorganizationupdate'),
path('admin/organization/detail/<int:pk>/', AdminOrganizationDetailView.as_view(), name = 'adminorganizationdetail'),


path('admin/image-album/add/', ImageAlbumAddView.as_view(), name = 'imagealbumadd'),
path('admin/imagealbum/list/', ImageAlbumListView.as_view(), name = 'imagealbumlist'),
# path('admin/imagealbum/<int:pk>/detail/', ImageAlbumDetailView.as_view(), name = 'adminimagealbumdetail'),
# path('admin/imagealbum/<int:pk>/update/', ImageAlbumUpdateView.as_view(), name = 'adminimagealbumupdate'),
# path('admin/imagealbum/<int:pk>/delete/', ImageAlbumDeleteView.as_view(), name = 'adminimagealbumdelete'),



path('',ClientIndexView.as_view(), name = 'indexpage' ),
path('contact-us/',ClientContactUsView.as_view(), name = 'clientcontactus' ),

]

fweanproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('fweanapp.urls')),
    # path('select2/',include('django_select2.urls')),
    path('summernote/', include('django_summernote.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admintemplates/admintemplate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/admintemplates/dashboard.html
{% extends 'admintemplates/adminbase.html' %}

{% block css %}

{% endblock %}

{% block content %}

 <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">Dashboard</h4>
                        <div class="ms-auto text-end">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">Library</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>


 <div class="container-fluid">

            <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"></h5>
                                <div class="row">
                                    <!-- Column -->

                                    <div class="col-md-6 col-lg-3 col-xlg-3">
                                         <a href="{% url 'fweanapp:adminorganizationdetail' org.id %}">
                                        <div class="card card-hover">
                                            <div style="height: 150px;" class="box bg-cyan text-center">
                                                <h1 class="font-light text-white mt-4 "><i class="mdi mdi-view-dashboard"></i>
                                                </h1>
                                                <h6 class="text-white">Organization</h6>
                                            </div>
                                        </div>
                                      </a>
                                    </div>

                                    <!-- Column -->
                                    <div class="col-md-6 col-lg-3 col-xlg-3">
                                         <a href="{% url 'fweanapp:imagealbumlist'  %}">
                                        <div class="card card-hover">
                                            <div style="height: 150px;" class="box bg-success text-center">
                                                <h1 class="font-light text-white mt-4"><i
                                                        class="mdi mdi-chart-areaspline"></i></h1>
                                                <h6 class="text-white">Image Albums (Gallery)</h6>
                                            </div>
                                        </div>
                                         </a>
                                    </div>
                                    <!-- Column -->
                                    <div class="col-md-6 col-lg-3 col-xlg-3">
                                        <div class="card card-hover">
                                            <div class="box bg-warning text-center">
                                                <h1 class="font-light text-white"><i class="mdi mdi-collage"></i></h1>
                                                <h6 class="text-white">Widgets</h6>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Column -->
                                    <div class="col-md-6 col-lg-3 col-xlg-3">
                                        <div class="card card-hover">
                                            <div class="box bg-danger text-center">
                                                <h1 class="font-light text-white"><i class="mdi mdi-border-outside"></i>
                                                </h1>
                                                <h6 class="text-white">Tables</h6>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Column -->
                                    <div class="col-md-6 col-lg-3 col-xlg-3">
                                        <div class="card card-hover">
                                            <div class="box bg-info text-center">
                                                <h1 class="font-light text-white"><i class="mdi mdi-arrow-all"></i></h1>
                                                <h6 class="text-white">Full Width</h6>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Column -->
                                    <!-- Column -->
                                    <div class="col-md-6 col-lg-3 col-xlg-3">
                                        <div class="card card-hover">
                                            <div class="box bg-danger text-center">
                                                <h1 class="font-light text-white"><i class="mdi mdi-receipt"></i></h1>
                                                <h6 class="text-white">Forms</h6>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Column -->
                                    <div class="col-md-6 col-lg-3 col-xlg-3">
                                        <div class="card card-hover">
                                            <div class="box bg-info text-center">
                                                <h1 class="font-light text-white"><i class="mdi mdi-relative-scale"></i>
                                                </h1>
                                                <h6 class="text-white">Buttons</h6>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Column -->
                                    <div class="col-md-6 col-lg-3 col-xlg-3">
                                        <div class="card card-hover">
                                            <div class="box bg-cyan text-center">
                                                <h1 class="font-light text-white"><i class="mdi mdi-pencil"></i></h1>
                                                <h6 class="text-white">Elements</h6>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Column -->
                                    <div class="col-md-6 col-lg-3 col-xlg-3">
                                        <div class="card card-hover">
                                            <div class="box bg-success text-center">
                                                <h1 class="font-light text-white"><i class="mdi mdi-calendar-check"></i>
                                                </h1>
                                                <h6 class="text-white">Calnedar</h6>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Column -->
                                    <div class="col-md-6 col-lg-3 col-xlg-3">
                                        <div class="card card-hover">
                                            <div class="box bg-info text-center">
                                                <h1 class="font-light text-white"><i class="mdi mdi-arrow-all"></i></h1>
                                                <h6 class="text-white">Full Width</h6>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Column -->
                                    <!-- Column -->
                                    <div class="col-md-6 col-lg-3 col-xlg-3">
                                        <div class="card card-hover">
                                            <div class="box bg-danger text-center">
                                                <h1 class="font-light text-white"><i class="mdi mdi-border-outside"></i>
                                                </h1>
                                                <h6 class="text-white">Tables</h6>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Column -->
                                    <div class="col-md-6 col-lg-3 col-xlg-3">
                                        <div class="card card-hover">
                                            <div class="box bg-warning text-center">
                                                <h1 class="font-light text-white"><i class="mdi mdi-alert"></i></h1>
                                                <h6 class="text-white">Errors</h6>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Column -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


 </div>



{% endblock %}

{% block js %}

{% endblock %}

templates/admintemplates/imagealbumadd.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block css %}

     <style>
    .add-row, .delete-row {
        margin-top: 5px;

    }
    </style>

{% endblock %}


{% block content %}
            <div class="container-fluid">
              <div   id="page-inner" xmlns="http://www.w3.org/1999/html">
			 <div class="row mt-2">
			 <div class="col-lg-12 ">
			 <div class="card container-fluid">
                        <div class="card-action">
                            <h3 class="text-center mt-3"> <strong> Add Albums and Image Medias </strong></h3>
                        </div>
                        <div class="card-content">
    <form class="col s12 " action = "" method = "post" enctype="multipart/form-data">
     <h3 class="text-center"> <strong> (Album field)</strong></h3>
        {% csrf_token %}
      <div class="row ">
        <div class=" col s6 ">

          <label class="text-darken-4">Title</label>
            {{ form.title }}
        </div>

         <div class="col s6">

          <label>Thumbnail:</label>
            {{ form.image }}
        </div>


      </div>


        <div class="row">
            <div class=" col-12">

          <label>Description</label>
            {{ form.description }}
        </div>


      </div>

        <div class="mt-3">
            <fieldset>
                <legend>
                    <h3 class="text-center"> <strong> (Images field) </strong></h3></legend>
                         {{ imagemedia_form.management_form}}
                        {{ imagemedia_form.non_form_errors }}

                          <div class="row">
                              {% for form in imagemedia_form.forms %}
                            <div class="col-sm">

                                <div class=" inline {{ imagemedia_form.prefix }}">

                                 <h1> {{ form.id }} </h1>

                                {{ form.image.errors }}
                                    {{ form.image.label_tag }}
                                    {{ form.image }}

                                    {{ form.title }}

                                     </div>



                                        </div>
                                           {% endfor %}

                                      </div>





                            </fieldset>



        </div>

         <div class="container bg-light">
        <div class="col-md-12 text-center mt-2">
            <button type="submit" class="btn btn-lg btn-primary">Submit</button>
           </div>
    </div>

    </form>
	<div class="clearBoth"></div>
  </div>
    </div>
 </div>
	 </div>
            </div>

            </div>
{% endblock %}

{% block js%}

    <script src="{% static 'adminstatic/base/dist/js/formset/jquery.formset.js' %}" ></script>

<script type="text/javascript">
        $(function() {
            $(".inline.{{ imagemedia_form.prefix }}").formset({
                prefix: "{{ imagemedia_form.prefix }}",
            })

        })
    </script>

{% endblock %}

templates/admintemplates/imagealbumdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/admintemplates/imagealbumlist.html
{% extends 'admintemplates/adminbase.html' %}

{% block css %}

<style>
body {
	color: #566787;
	background: #f5f5f5;
	font-family: 'Varela Round', sans-serif;
	font-size: 13px;
}
.table-responsive {
    margin: 30px 0;
}
.table-wrapper {
	background: #fff;
	padding: 20px 25px;
	border-radius: 3px;
	min-width: 1000px;
	box-shadow: 0 1px 1px rgba(0,0,0,.05);
}
.table-title {
	padding-bottom: 15px;
	background: #435d7d;
	color: #fff;
	padding: 16px 30px;
	min-width: 100%;
	margin: -20px -25px 10px;
	border-radius: 3px 3px 0 0;
}
.table-title h2 {
	margin: 5px 0 0;
	font-size: 24px;
}
.table-title .btn-group {
	float: right;
}
.table-title .btn {
	color: #fff;
	float: right;
	font-size: 13px;
	border: none;
	min-width: 50px;
	border-radius: 2px;
	border: none;
	outline: none !important;
	margin-left: 10px;
}
.table-title .btn i {
	float: left;
	font-size: 21px;
	margin-right: 5px;
}
.table-title .btn span {
	float: left;
	margin-top: 2px;
}
table.table tr th, table.table tr td {
	border-color: #e9e9e9;
	padding: 12px 15px;
	vertical-align: middle;
}
table.table tr th:first-child {
	width: 60px;
}
table.table tr th:last-child {
	width: 100px;
}
table.table-striped tbody tr:nth-of-type(odd) {
	background-color: #fcfcfc;
}
table.table-striped.table-hover tbody tr:hover {
	background: #f5f5f5;
}
table.table th i {
	font-size: 13px;
	margin: 0 5px;
	cursor: pointer;
}
table.table td:last-child i {
	opacity: 0.9;
	font-size: 22px;
	margin: 0 5px;
}
table.table td a {
	font-weight: bold;
	color: #566787;
	display: inline-block;
	text-decoration: none;
	outline: none !important;
}
table.table td a:hover {
	color: #2196F3;
}
table.table td a.edit {
	color: #FFC107;
}
table.table td a.delete {
	color: #F44336;
}
table.table td i {
	font-size: 19px;
}
table.table .avatar {
	border-radius: 50%;
	vertical-align: middle;
	margin-right: 10px;
}
.pagination {
	float: right;
	margin: 0 0 5px;
}
.pagination li a {
	border: none;
	font-size: 13px;
	min-width: 30px;
	min-height: 30px;
	color: #999;
	margin: 0 2px;
	line-height: 30px;
	border-radius: 2px !important;
	text-align: center;
	padding: 0 6px;
}
.pagination li a:hover {
	color: #666;
}
.pagination li.active a, .pagination li.active a.page-link {
	background: #03A9F4;
}
.pagination li.active a:hover {
	background: #0397d6;
}
.pagination li.disabled i {
	color: #ccc;
}
.pagination li i {
	font-size: 16px;
	padding-top: 6px
}
.hint-text {
	float: left;
	margin-top: 10px;
	font-size: 13px;
}
/* Custom checkbox */
.custom-checkbox {
	position: relative;
}
.custom-checkbox input[type="checkbox"] {
	opacity: 0;
	position: absolute;
	margin: 5px 0 0 3px;
	z-index: 9;
}
.custom-checkbox label:before{
	width: 18px;
	height: 18px;
}
.custom-checkbox label:before {
	content: '';
	margin-right: 10px;
	display: inline-block;
	vertical-align: text-top;
	background: white;
	border: 1px solid #bbb;
	border-radius: 2px;
	box-sizing: border-box;
	z-index: 2;
}
.custom-checkbox input[type="checkbox"]:checked + label:after {
	content: '';
	position: absolute;
	left: 6px;
	top: 3px;
	width: 6px;
	height: 11px;
	border: solid #000;
	border-width: 0 3px 3px 0;
	transform: inherit;
	z-index: 3;
	transform: rotateZ(45deg);
}
.custom-checkbox input[type="checkbox"]:checked + label:before {
	border-color: #03A9F4;
	background: #03A9F4;
}
.custom-checkbox input[type="checkbox"]:checked + label:after {
	border-color: #fff;
}
.custom-checkbox input[type="checkbox"]:disabled + label:before {
	color: #b8b8b8;
	cursor: auto;
	box-shadow: none;
	background: #ddd;
}
/* Modal styles */
.modal .modal-dialog {
	max-width: 400px;
}
.modal .modal-header, .modal .modal-body, .modal .modal-footer {
	padding: 20px 30px;
}
.modal .modal-content {
	border-radius: 3px;
	font-size: 14px;
}
.modal .modal-footer {
	background: #ecf0f1;
	border-radius: 0 0 3px 3px;
}
.modal .modal-title {
	display: inline-block;
}
.modal .form-control {
	border-radius: 2px;
	box-shadow: none;
	border-color: #dddddd;
}
.modal textarea.form-control {
	resize: vertical;
}
.modal .btn {
	border-radius: 2px;
	min-width: 100px;
}
.modal form label {
	font-weight: normal;
}
</style>
    


{% endblock %}

{% block content %}


    <div class="container-xl">
	<div class="table-responsive">
		<div class="table-wrapper">
			<div class="table-title">
				<div class="row">
					<div class="col-sm-6">
						<h2>Manage <b>Albums (Gallery)</b></h2>
					</div>
					<div class="col-sm-6">
                        <a href="{% url 'fweanapp:imagealbumadd' %}"><div class="btn btn-success" data-toggle="modal"><i class="fas fa-plus-circle">&#xE147;</i> <span>Add New Album</span></div></a>
{#						<a href="#deleteEmployeeModal" class="btn btn-danger" data-toggle="modal"><i class="fas fa-minus-circle">&#xE15C;</i> <span>Delete</span></a>#}

                    </div>
				</div>
			</div>
			<table class="table table-striped table-hover">
				<thead>
					<tr class="h4">

						<th>S.N</th>
						<th>Title</th>
						<th>Album Thumbnail</th>
						<th>Description</th>
						<th>Details</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
                         {% for album in albums %}

                      <tr>

						<td>{{ forloop.counter}}.</td>
						<td>{{ album.title}}</td>
						<td><img style="width: 50px; height: 40px;" src="{{ album.image.url }}" alt=""></td>
						<td>{{ album.description}}</td>

                           <td>
                                                    <a href="#"><button class="btn btn-sm btn-success">View Details</button></a>
                                        </td>
						<td>
							<a href="#editEmployeeModal" class="edit" data-toggle="modal"><i class="fas fa-pencil-alt" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
							<a href="#deleteEmployeeModal" class="delete" data-toggle="modal"><i class="fas fa-trash" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
						</td>
					</tr>

                {% endfor %}
				</tbody>
			</table>
			<div class="clearfix">
				<div class="hint-text">Showing <b>5</b> out of <b>25</b> entries</div>
				<ul class="pagination">
					<li class="page-item disabled"><a href="#">Previous</a></li>
					<li class="page-item"><a href="#" class="page-link">1</a></li>
					<li class="page-item"><a href="#" class="page-link">2</a></li>
					<li class="page-item "><a href="#" class="page-link">3</a></li>
					<li class="page-item"><a href="#" class="page-link">4</a></li>
					<li class="page-item"><a href="#" class="page-link">5</a></li>
					<li class="page-item"><a href="#" class="page-link">Next</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<!-- Edit Modal HTML -->
<div id="addEmployeeModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<form>
				<div class="modal-header">
					<h4 class="modal-title">Add Employee</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">
					<div class="form-group">
						<label>Name</label>
						<input type="text" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Email</label>
						<input type="email" class="form-control" required>
					</div>
					<div class="form-group">
						<label>Address</label>
						<textarea class="form-control" required></textarea>
					</div>
					<div class="form-group">
						<label>Phone</label>
						<input type="text" class="form-control" required>
					</div>
				</div>
				<div class="modal-footer">
					<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
					<input type="submit" class="btn btn-success" value="Add">
				</div>
			</form>
		</div>
	</div>
</div>
<!-- Edit Modal HTML -->

<!-- Delete Modal HTML -->
<div id="deleteEmployeeModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<form>
				<div class="modal-header">
					<h4 class="modal-title">Delete Employee</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">
					<p>Are you sure you want to delete these Records?</p>
					<p class="text-warning"><small>This action cannot be undone.</small></p>
				</div>
				<div class="modal-footer">
					<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
					<input type="submit" class="btn btn-danger" value="Delete">
				</div>
			</form>
		</div>
	</div>
</div>


{% endblock %}

{% block js %}


{% endblock %}

templates/admintemplates/organizationdetail.html
{% extends 'admintemplates/adminbase.html' %}

{% block css %}

{% endblock %}

{% block content %}

    <div class="container-fluid">

      <div class="table-responsive">

   <table class="table table-striped table-bordered table-hover">

        <thead class="bg-success">
         <tr>


        <th class="center " style="height: 50px" colspan='2' > <h3>Organization Info!!!

            {% if not org %}

                        <a class="ml-20"> <a href="{% url 'fweanapp:adminorganizationcreate'  %}" > <button class="btn btn-lg btn-primary "> Add new </button>  </a>

                            {% endif %}
                            {% if  org %}

                             <a href="{% url 'fweanapp:adminorganizationupdate' org.id %}" > <button class="btn btn-lg btn-warning"> Update </button> </a>

                            {% endif %}

                     </h3>


        </th>

        </tr>
        </thead>
        <tbody>
            <tr>
      <th><b>Name:</b></th>
      <td>{{ org.name }}</td>

    </tr>
    <tr>
      <th><b>Logo:</b></th>
      <td> <img  src="{{org.logo.url}}" alt="" style="width: 200px;"></td>

    </tr>
    <tr>
      <th><b>Profile Image:</b></th>
      <td><img src="{{org.profile_image.url}}" alt="" style="width: 200px;"></td>

    </tr>

  <tr>
      <th><b>Address</b></th>
      <td>{{ org.address }}</td>

    </tr>

  <tr>
      <th><b>Contact No:</b></th>
      <td>{{ org.contact_no }}</td>

    </tr>

   <tr>
      <th><b> Alternative Contact No:</b></th>
      <td>{{ org.alt_contact_no }}</td>

    </tr>


   <tr>
      <th><b>Map Location:</b></th>
      <td>{{ org.map_location|truncatechars_html:100 }}</td>

    </tr>

   <tr>
      <th><b>Email:</b></th>
      <td>{{ org.email }}</td>

    </tr>
   <tr>
      <th><b>Alternative Email:</b></th>
      <td>{{ org.alt_email }}</td>

    </tr>

            <tr>
      <th><b>Facilities:</b></th>
      <td>
          {% for  facilities in org.facilities.all %}
          {{ facilities }},
          {% endfor %}
      </td>

    </tr>

   <tr>
      <th><b>About Us:</b></th>
      <td>{{ org.about_us }}</td>

    </tr>

   <tr>
      <th><b>Missiion Vision:</b></th>
      <td>{{ org.mission_vision }}</td>

    </tr>

   <tr>
      <th><b>Facebook:</b></th>
      <td>{{ org.facebook }}</td>

    </tr>

    <tr>
      <th><b>Instagram:</b></th>
      <td>{{ org.instagram }}</td>

    </tr>
    <tr>
      <th><b>Twitter:</b></th>
      <td>{{ org.twitter }}</td>

    </tr>

    <tr>
      <th><b>Youtube:</b></th>
      <td>{{ org.youtube}}</td>

    </tr>

    <tr>
      <th><b>Viber:</b></th>
      <td>{{ org.viber }}</td>

    </tr>

    <tr>
      <th><b>Whatsapp:</b></th>
      <td>{{ org.whatsapp }}</td>

    </tr>

    <tr>
      <th><b>Terms and Condition:</b></th>
      <td >{{ org.terms_and_conditions|safe }}</td>

    </tr>
  <tr>
      <th><b>Privacy Policy:</b></th>
      <td>{{ org.privacy_policy|safe }}</td>

    </tr>
  </tbody>



                                </table>
                            </div>

    </div>


{% endblock %}